/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: statsmessage.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "statsmessage.pb-c.h"
void   stats_request__init
                     (StatsRequest         *message)
{
  static StatsRequest init_value = STATS_REQUEST__INIT;
  *message = init_value;
}
size_t stats_request__get_packed_size
                     (const StatsRequest *message)
{
  assert(message->base.descriptor == &stats_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t stats_request__pack
                     (const StatsRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &stats_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t stats_request__pack_to_buffer
                     (const StatsRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &stats_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
StatsRequest *
       stats_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (StatsRequest *)
     protobuf_c_message_unpack (&stats_request__descriptor,
                                allocator, len, data);
}
void   stats_request__free_unpacked
                     (StatsRequest *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &stats_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   msg_cell__init
                     (MsgCell         *message)
{
  static MsgCell init_value = MSG_CELL__INIT;
  *message = init_value;
}
size_t msg_cell__get_packed_size
                     (const MsgCell *message)
{
  assert(message->base.descriptor == &msg_cell__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t msg_cell__pack
                     (const MsgCell *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &msg_cell__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t msg_cell__pack_to_buffer
                     (const MsgCell *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &msg_cell__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MsgCell *
       msg_cell__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MsgCell *)
     protobuf_c_message_unpack (&msg_cell__descriptor,
                                allocator, len, data);
}
void   msg_cell__free_unpacked
                     (MsgCell *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &msg_cell__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   stats_reply__init
                     (StatsReply         *message)
{
  static StatsReply init_value = STATS_REPLY__INIT;
  *message = init_value;
}
size_t stats_reply__get_packed_size
                     (const StatsReply *message)
{
  assert(message->base.descriptor == &stats_reply__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t stats_reply__pack
                     (const StatsReply *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &stats_reply__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t stats_reply__pack_to_buffer
                     (const StatsReply *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &stats_reply__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
StatsReply *
       stats_reply__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (StatsReply *)
     protobuf_c_message_unpack (&stats_reply__descriptor,
                                allocator, len, data);
}
void   stats_reply__free_unpacked
                     (StatsReply *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &stats_reply__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor stats_request__field_descriptors[3] =
{
  {
    "key",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(StatsRequest, key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "view",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(StatsRequest, view),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "topn",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(StatsRequest, has_topn),
    offsetof(StatsRequest, topn),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned stats_request__field_indices_by_name[] = {
  0,   /* field[0] = key */
  2,   /* field[2] = topn */
  1,   /* field[1] = view */
};
static const ProtobufCIntRange stats_request__number_ranges[1 + 1] =
{
  { 2, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor stats_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "StatsRequest",
  "StatsRequest",
  "StatsRequest",
  "",
  sizeof(StatsRequest),
  3,
  stats_request__field_descriptors,
  stats_request__field_indices_by_name,
  1,  stats_request__number_ranges,
  (ProtobufCMessageInit) stats_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor msg_cell__field_descriptors[2] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(MsgCell, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "count",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(MsgCell, has_count),
    offsetof(MsgCell, count),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned msg_cell__field_indices_by_name[] = {
  1,   /* field[1] = count */
  0,   /* field[0] = name */
};
static const ProtobufCIntRange msg_cell__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor msg_cell__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "MsgCell",
  "MsgCell",
  "MsgCell",
  "",
  sizeof(MsgCell),
  2,
  msg_cell__field_descriptors,
  msg_cell__field_indices_by_name,
  1,  msg_cell__number_ranges,
  (ProtobufCMessageInit) msg_cell__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor stats_reply__field_descriptors[13] =
{
  {
    "key",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(StatsReply, key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "maybe",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(StatsReply, maybe),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(StatsReply, has_value),
    offsetof(StatsReply, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "result",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(StatsReply, n_result),
    offsetof(StatsReply, result),
    &msg_cell__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    6,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(StatsReply, n_name),
    offsetof(StatsReply, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "count",
    7,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(StatsReply, n_count),
    offsetof(StatsReply, count),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rate",
    8,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(StatsReply, n_rate),
    offsetof(StatsReply, rate),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "access_count",
    9,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(StatsReply, n_access_count),
    offsetof(StatsReply, access_count),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bandwidth",
    10,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(StatsReply, n_bandwidth),
    offsetof(StatsReply, bandwidth),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hit_count",
    11,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(StatsReply, n_hit_count),
    offsetof(StatsReply, hit_count),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hit_bandwidth",
    12,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(StatsReply, n_hit_bandwidth),
    offsetof(StatsReply, hit_bandwidth),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lost_count",
    13,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(StatsReply, n_lost_count),
    offsetof(StatsReply, lost_count),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lost_bandwidth",
    14,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(StatsReply, n_lost_bandwidth),
    offsetof(StatsReply, lost_bandwidth),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned stats_reply__field_indices_by_name[] = {
  7,   /* field[7] = access_count */
  8,   /* field[8] = bandwidth */
  5,   /* field[5] = count */
  10,   /* field[10] = hit_bandwidth */
  9,   /* field[9] = hit_count */
  0,   /* field[0] = key */
  12,   /* field[12] = lost_bandwidth */
  11,   /* field[11] = lost_count */
  1,   /* field[1] = maybe */
  4,   /* field[4] = name */
  6,   /* field[6] = rate */
  3,   /* field[3] = result */
  2,   /* field[2] = value */
};
static const ProtobufCIntRange stats_reply__number_ranges[1 + 1] =
{
  { 2, 0 },
  { 0, 13 }
};
const ProtobufCMessageDescriptor stats_reply__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "StatsReply",
  "StatsReply",
  "StatsReply",
  "",
  sizeof(StatsReply),
  13,
  stats_reply__field_descriptors,
  stats_reply__field_indices_by_name,
  1,  stats_reply__number_ranges,
  (ProtobufCMessageInit) stats_reply__init,
  NULL,NULL,NULL    /* reserved[123] */
};
